### ISSUE TITLE
How are weigths of layer "LinearizedConvolution" initialized?

### ISSUE THREAD

**Issue by weilheim** [facebookresearch/fairseq-py#10]
I would like to use your Conv S2S model in another task, so I hope to know the details of the model.
I have read the code defining class "LinearizedConvolution" and its parent layer "ConvTBC", however, I haven't seen any code doing weight initialization.

Could you please let me know how weigths of layer "LinearizedConvolution" are initialized?
Thanks!

**Comment by myleott** [comment]
Weight initialization happens here: https://github.com/facebookresearch/fairseq-py/blob/master/fairseq/models/fconv.py#L405-L407
