### ISSUE TITLE
Can't generate target sequence with more than 200 tokens

### ISSUE THREAD

**Issue by wojtekcz** [facebookresearch/fairseq-py#100]
There is hardcoded (hidded) limit of maxlen=200 tokens in SequenceGenerator constructor that can't be increased in generate.py not interactive.py scripts.

It's strange since training with default parameters analyzes 1024 target positions.

Should we pass --max-target-positions value to SequenceGenerator constructor?

The limit can't be increased by --max-len-a and --max-len-b arguments. It can only be lowered per sentence which is understandable.

Does it make sense to maybe create new --max-sequence-len command line argument?

**Comment by myleott** [comment]
Good catch, we should adjust the default maxlen to be the decoder's max positions, rather than a fixed value of 200. Will submit a fix shortly.
