### ISSUE TITLE
Errors after training 1 epoch

### ISSUE THREAD

**Issue by getao** [facebookresearch/fairseq-py#102]
Hello, I found the following error after training 1 epoch:

  File "train.py", line 201, in train
    ('train loss', round(loss_meter.avg, 2)),
TypeError: type Variable doesn't define __round__ method

Can anyone help me with the case?

Thank you

**Comment by edunov** [comment]
@getao could you provide more details, please? In particular: entire log, your setup (pytorch version and whether you use latest fairseq-py), and what command are you running?

**Comment by getao** [comment]
Here is the complete error message:

Traceback (most recent call last):
  File "train.py", line 294, in <module>
    main()
  File "train.py", line 111, in main
    train(args, epoch, batch_offset, trainer, dataset, max_positions_train)
  File "train.py", line 201, in train
    ('train loss', round(loss_meter.avg, 2)),
TypeError: type Variable doesn't define __round__ method

The log is very long. The error just occurs after finishing training epoch 001: 100%.
My pytorch is 0.4.0
My command line is CUDA_VISIBLE_DEVICES=0,1 python train.py data-bin/nmt/ --lr 0.25  --clip-norm 0.1 --dropout 0.2 --arch fconv --save-dir checkpoints/fconv_nmt

**Comment by edunov** [comment]
The issue should be fixed in the latest version of fairseq-py: #107
