### ISSUE TITLE
Using more than 1 GPU

### ISSUE THREAD

**Issue by enferas** [facebookresearch/fairseq-py#117]
I am using a machine with 16 GPUs.
But with the training. they write "training on 1 GPUs"

```
[de] dictionary: 10433 types                               
[en] dictionary: 10389 types                               
data-bin/iwslt14.tokenized.de-en train 6377123 examples    
data-bin/iwslt14.tokenized.de-en valid 297921 examples     
model fconv_iwslt_de_en, criterion CrossEntropyCriterion   
num. model params: 11955242                                
training on 1 GPUs                                         
max tokens per GPU = 4000 and max sentences per GPU = None 
```

Is that meaning I am using just 1 GPU. and is there any thing I should edit to make all the GPUs work ?

**Comment by enferas** [comment]
I was using this command:

```
CUDA_VISIBLE_DEVICES=0 python train.py data-bin/iwslt14.tokenized.de-en \
  --lr 0.25 --clip-norm 0.1 --dropout 0.2 --max-tokens 4000 \
  --arch fconv_iwslt_de_en --save-dir checkpoints/fconv
```

So I changed CUDA_VISIBLE_DEVICES to be 0 and 1:

```
CUDA_VISIBLE_DEVICES=0,1 python train.py data-bin/iwslt14.tokenized.de-en \
  --lr 0.25 --clip-norm 0.1 --dropout 0.2 --max-tokens 4000 \
  --arch fconv_iwslt_de_en --save-dir checkpoints/fconv
```

but then it is give me this error:

`RuntimeError: the distributed NCCL backend is not available; try to recompile the THD package with CUDA and NCCL 2+ support at /home/ubuntu/pytorch4/pytorch/torch/lib/THD/process_group/General.cpp:17`

**Comment by edunov** [comment]
@enferas you need to install the latest pytorch from the source as described here: https://github.com/pytorch/pytorch#installation  

Please also make sure you have NCCL2 installed
