### ISSUE TITLE
Increasing loss in a summarization task

### ISSUE THREAD

**Issue by shashiongithub** [facebookresearch/fairseq-py#118]
Hi,

I am running your code on a news summarization task similar to the CNN and Dailymail datasets. It looks okay  in the beginning but at some point (in epoch 1) gnorm starts to increase which leads to loss and ppl to explode. Note that the source (article) could have 400 tokens. 

I am using: --max-sentences 32 --arch fconv --criterion label_smoothed_cross_entropy --clip-norm 0.1 --lr 0.20 --dropout 0.2 

The time it explodes:

| epoch 001:   1660 / 11138 loss=9.405, ppl=677.75, wps=1440, ups=3.2, wpb=444, bsz=18, num_updates=1661, lr=0.2, gnorm=2.602, clip=100%, oom=0
| epoch 001:   1670 / 11138 loss=9.399, ppl=674.97, wps=1440, ups=3.2, wpb=444, bsz=18, num_updates=1671, lr=0.2, gnorm=2.592, clip=100%, oom=0
| epoch 001:   1680 / 11138 loss=9.393, ppl=672.28, wps=1439, ups=3.2, wpb=444, bsz=18, num_updates=1681, lr=0.2, gnorm=2.583, clip=100%, oom=0
| epoch 001:   1690 / 11138 loss=9.387, ppl=669.56, wps=1439, ups=3.2, wpb=444, bsz=18, num_updates=1691, lr=0.2, gnorm=2.638, clip=100%, oom=0
| epoch 001:   1700 / 11138 loss=9.382, ppl=666.99, wps=1439, ups=3.2, wpb=444, bsz=18, num_updates=1701, lr=0.2, gnorm=2.804, clip=100%, oom=0
| epoch 001:   1710 / 11138 loss=9.378, ppl=665.57, wps=1436, ups=3.2, wpb=443, bsz=18, num_updates=1711, lr=0.2, gnorm=3.434, clip=100%, oom=0
| epoch 001:   1720 / 11138 loss=9.372, ppl=662.58, wps=1436, ups=3.2, wpb=443, bsz=18, num_updates=1721, lr=0.2, gnorm=3.423, clip=100%, oom=0
| epoch 001:   1730 / 11138 loss=9.365, ppl=659.26, wps=1438, ups=3.2, wpb=444, bsz=18, num_updates=1731, lr=0.2, gnorm=3.410, clip=100%, oom=0
| epoch 001:   1740 / 11138 loss=9.360, ppl=656.91, wps=1438, ups=3.2, wpb=444, bsz=18, num_updates=1741, lr=0.2, gnorm=3.461, clip=100%, oom=0
| epoch 001:   1750 / 11138 loss=9.355, ppl=655.06, wps=1437, ups=3.2, wpb=444, bsz=18, num_updates=1751, lr=0.2, gnorm=7.333, clip=100%, oom=0
| epoch 001:   1760 / 11138 loss=9.352, ppl=653.70, wps=1437, ups=3.2, wpb=443, bsz=18, num_updates=1761, lr=0.2, gnorm=7.974, clip=100%, oom=0
| epoch 001:   1770 / 11138 loss=9.349, ppl=651.98, wps=1436, ups=3.2, wpb=443, bsz=18, num_updates=1771, lr=0.2, gnorm=8.668, clip=100%, oom=0
| epoch 001:   1780 / 11138 loss=9.346, ppl=650.57, wps=1436, ups=3.2, wpb=443, bsz=18, num_updates=1781, lr=0.2, gnorm=24.866, clip=100%, oom=0
| epoch 001:   1790 / 11138 loss=9.342, ppl=649.07, wps=1438, ups=3.2, wpb=444, bsz=18, num_updates=1791, lr=0.2, gnorm=29.790, clip=100%, oom=0
| epoch 001:   1800 / 11138 loss=9.341, ppl=648.63, wps=1438, ups=3.2, wpb=444, bsz=18, num_updates=1801, lr=0.2, gnorm=38.178, clip=100%, oom=0
| epoch 001:   1810 / 11138 loss=9.340, ppl=647.91, wps=1439, ups=3.2, wpb=444, bsz=18, num_updates=1811, lr=0.2, gnorm=47.127, clip=100%, oom=0
| epoch 001:   1820 / 11138 loss=9.335, ppl=645.62, wps=1440, ups=3.2, wpb=445, bsz=18, num_updates=1821, lr=0.2, gnorm=51.265, clip=100%, oom=0
| epoch 001:   1830 / 11138 loss=9.333, ppl=644.92, wps=1441, ups=3.2, wpb=445, bsz=18, num_updates=1831, lr=0.2, gnorm=63.347, clip=100%, oom=0
| epoch 001:   1840 / 11138 loss=9.333, ppl=645.08, wps=1441, ups=3.2, wpb=445, bsz=18, num_updates=1841, lr=0.2, gnorm=133.010, clip=100%, oom=0
| epoch 001:   1850 / 11138 loss=9.340, ppl=647.85, wps=1440, ups=3.2, wpb=445, bsz=18, num_updates=1851, lr=0.2, gnorm=242.123, clip=100%, oom=0
| epoch 001:   1860 / 11138 loss=9.350, ppl=652.41, wps=1441, ups=3.2, wpb=445, bsz=18, num_updates=1861, lr=0.2, gnorm=343.637, clip=100%, oom=0
...
| epoch 001:   1990 / 11138 loss=9.732, ppl=850.36, wps=1440, ups=3.2, wpb=444, bsz=18, num_updates=1991, lr=0.2, gnorm=10664.608, clip=100%, oom=0
| epoch 001:   2000 / 11138 loss=9.799, ppl=890.65, wps=1439, ups=3.2, wpb=444, bsz=18, num_updates=2001, lr=0.2, gnorm=15569.126, clip=100%, oom=0
| epoch 001:   2010 / 11138 loss=9.878, ppl=941.22, wps=1439, ups=3.2, wpb=444, bsz=18, num_updates=2011, lr=0.2, gnorm=21505.205, clip=100%, oom=0
| epoch 001:   2020 / 11138 loss=9.984, ppl=1012.55, wps=1438, ups=3.2, wpb=444, bsz=18, num_updates=2021, lr=0.2, gnorm=62536.300, clip=100%, oom=0
| epoch 001:   2030 / 11138 loss=10.136, ppl=1125.13, wps=1437, ups=3.2, wpb=444, bsz=18, num_updates=2031, lr=0.2, gnorm=83845.732, clip=100%, oom=0
| epoch 001:   2040 / 11138 loss=10.331, ppl=1288.10, wps=1438, ups=3.2, wpb=444, bsz=18, num_updates=2041, lr=0.2, gnorm=121786.232, clip=100%, oom=0
| epoch 001:   2050 / 11138 loss=10.615, ppl=1567.78, wps=1438, ups=3.2, wpb=444, bsz=18, num_updates=2051, lr=0.2, gnorm=330414.449, clip=100%, oom=0
| epoch 001:   2060 / 11138 loss=11.007, ppl=2058.19, wps=1438, ups=3.2, wpb=444, bsz=18, num_updates=2061, lr=0.2, gnorm=491862.140, clip=100%, oom=0
| epoch 001:   2070 / 11138 loss=11.621, ppl=3148.97, wps=1437, ups=3.2, wpb=444, bsz=18, num_updates=2071, lr=0.2, gnorm=1051417.148, clip=100%, oom=0
| epoch 001:   2080 / 11138 loss=12.817, ppl=7214.82, wps=1437, ups=3.2, wpb=444, bsz=18, num_updates=2081, lr=0.2, gnorm=8845659.733, clip=100%, oom=0
| epoch 001:   2090 / 11138 loss=18.015, ppl=264816.33, wps=1438, ups=3.2, wpb=444, bsz=18, num_updates=2091, lr=0.2, gnorm=74255205.498, clip=100%, oom=0
| epoch 001:   2100 / 11138 loss=30.752, ppl=1808081157.20, wps=1439, ups=3.2, wpb=444, bsz=18, num_updates=2101, lr=0.2, gnorm=153515178.483, clip=100%, oom=0
| epoch 001:   2110 / 11138 loss=54.073, ppl=18946421977714940.00, wps=1438, ups=3.2, wpb=444, bsz=18, num_updates=2111, lr=0.2, gnorm=778157410.126, clip=100%, oom=0
| epoch 001:   2120 / 11138 loss=101.822, ppl=4483007321633420545162320281600.00, wps=1438, ups=3.2, wpb=444, bsz=18, num_updates=2121, lr=0.2, gnorm=1701768751.091, clip=100%, oom=0
| epoch 001:   2130 / 11138 loss=145.502, 

Am I doing something wrong, could you please help?

Thanks for your code!

**Comment by sai-prasanna** [comment]
Tried a smaller learning rate ?

**Comment by shashiongithub** [comment]
Thanks, sai-prasanna! I am trying now with lr=0.1, gnorm is still increasing at some point but does not explode.
