### ISSUE TITLE
Conv1d instead of LinearizedConvolution and convTBC

### ISSUE THREAD

**Issue by piyank22** [facebookresearch/fairseq-py#12]
I am trying to implement a simpler version of this code and am finding it very difficult to see how linearizedConv and ConvTBC is used instead of simply conv1d , a intuition why such a task is done and why there are two different scheme is used in encoder and decoder.

**Comment by myleott** [comment]
ConvTBC and LinearizedConvolution are mostly equivalent to Conv1d, but are optimized to improve training and inference speed. They are both present in the original Lua version of the code as well.

Compared to Conv1d:
- ConvTBC takes input in a different shape (Time x Batch x Channel). This format avoids transposes in the attention layers and is faster than Conv1d for this model architecture.

**Comment by myleott** [comment]
ConvTBC and LinearizedConvolution are mostly equivalent to Conv1d, but are optimized to improve training and inference speed. They are both present in the original Lua version of the code as well.

Compared to Conv1d:
- ConvTBC takes input in a different shape (Time x Batch x Channel) and is more optimized for this model architecture.
- LinearizedConvolution improves inference speed by buffering the convolution from previous time steps, since generation/inference typically happens incrementally.

I can share a diff in a bit that replaces with plain Conv1d layers if that's be helpful.

**Comment by myleott** [comment]
ConvTBC and LinearizedConvolution are mostly equivalent to Conv1d, but are optimized to improve training and inference speed. They are both present in the original Lua version of the code as well.

Compared to Conv1d:
- ConvTBC takes input in a different shape (Time x Batch x Channel) and is more optimized for this model architecture.
- LinearizedConvolution improves inference speed by buffering the convolution from previous time steps and using a plain Linear layer, since generation/inference typically happens incrementally.

I can share a diff in a bit that replaces these with plain Conv1d layers if that'd be helpful.

**Comment by piyank22** [comment]
one follow up question if these are optimised version of Conv1d , why is (if you are familiar) Conv1d not following that routine and ,
Is this subroutine always theoretically a more optimised version. Thanks.

I am facing difficulties in understanding exactly how the decoder is working, 
as per my knowledge this is the first model with the convolution in the decoder part , hence the confusion and there isn't any resource available to explain it , neither can i find blog posts , so if you are familiar either point me to relevant secondary resource , if not ,

padding is initialised  as kernel-1 , 
in the [GIF](https://github.com/facebookresearch/fairseq-py/blob/master/fairseq.gif) in your documentation i see that initially we start from <pad> <pad> <start> ,
so here the kernel would be 3 , it shows that conv is being performed between two , which seems wrong,
am i interpreting the GIF incorrectly or should i not trust fancy visualization,

according to me ,
padding should be the same as in the encoder (pad-1)//2

and initially we are perform conv on (ignoring the paddings)

<start>  to  <intermediate> to  <intermediate> .. and then with attention predict the next word,

now it should become,

<start> <le>  to  <intermediate><intermediate> to <intermediate><intermediate> ...
and then keep on adding terms , and stop when we see end has come 
 
vs the way the diagram depicts,

<pad> <pad> <start> to <intermediate> to <intermediate> .... 
<pad> <pad> <start> <le> to <intermediate><intermediate> to <intermediate><intermediate> ...

and stop when we see the end token,
the reason i see you have done this way is to keep the number of pad's constant ( kernel being odd of course ) 
again please take the burden to help me out 
thanks a ton

**Comment by myleott** [comment]
The best source of information about the convolution decoder is probably the original paper: https://arxiv.org/abs/1705.03122.

Some background: Ordinarily for ConvTBC, the weight tensor is of size `[kw, in_channels, out_channels]`. In LinearizedConvolution we reshape the weight tensor to `[out_channels, kw*in_channels]`. This allows us to perform the convolution (for a single time step) using a simple `Linear(kw*in_channels, out_channels)` layer.

Now, convolutions behave like a sliding window over the input. For example, suppose our convolution at `t_{i-1}` is over `[A, B, C]` and at `t_i` is over `[B, C, D]`, thus the `[B, C]` part can be cached and reused at `t_i`. LinearizedConvolution does this by maintaining an internal buffer which is shifted by one position every time it gets a new input: https://github.com/facebookresearch/fairseq-py/blob/master/fairseq/modules/linearized_convolution.py#L60-L63.

Regarding the initial time steps, both Conv1d and LinearizedConvolution implicitly left-pad the input with 0s. In the case of LinearizedConvolution, the input buffer is initialized to 0s and new inputs are pushed onto the right side of the buffer (thus is implicitly 0-padded in the beginning).

Regarding your question in #14, note that during inference (i.e., incremental_forward) LinearizedConvolution only consumes the right-most time step of the input. Thus if the input is of size `[bsz, len, dim]`, it will only consume `input[:, -1, :]`, shift the buffer left, append the latest timestep of input to the buffer, and compute the new convolution (using a Linear layer as I described above).

**Comment by piyank22** [comment]
Thanks a lot.
summarising, when we are performing convolution by a window of size k  , we already have the convolution of k-1 step with us and we only need add it over the last row so a simple linear transformation works.
this if i understood is very overwhelming for me i will stick with the standard nn.conv1d , is the penalty due to this significantly very large if u have tried it out so.

**Comment by myleott** [comment]
Here is a diff that removes ConvTBC and LinearizedConvolution, replacing them with ordinary Conv1d layers. This code is significantly slower, but is also somewhat simpler.

Commit is here: https://github.com/facebookresearch/fairseq-py/commit/b584b8ae045c5c1d258c88dfec0d20daca63cfe0

**Comment by piyank22** [comment]
THANKS A LOT,
I am truly grateful, I was able to figure out ConvTBC by myself but i was facing tremendous difficulty in visualising how the LinearizedConvolution and the _incremental_forward function was working out but with the tremendous efforts put in by you, now I am able to read the code and understand the flow. 
Keep up your great work Sir.
Much Thanks
