### ISSUE TITLE
Error python setup.py build

### ISSUE THREAD

**Issue by michellegiang** [facebookresearch/fairseq-py#120]
Hi,

I have this problem when run python setup.py build, with the old version of fairseq-py (I used a model in https://github.com/nusnlp/mlconvgec2018, which used the old version of fairseq-py) and new version of PyTorch. Could you let me know how to solve it ? Thank you for your support

running build
running build_py
generating /tmp/tmpzgrxjknn/_temporal_convolution_tbc.c
setting the current directory to '/tmp/tmpzgrxjknn'
running build_ext
building '_temporal_convolution_tbc' extension
creating home
creating home/michelle
creating home/michelle/mlc
creating home/michelle/mlc/mlconvgec2018
creating home/michelle/mlc/mlconvgec2018/software
creating home/michelle/mlc/mlconvgec2018/software/fairseq-py
creating home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq
creating home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib
creating home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc
gcc -pthread -B /home/michelle/anaconda3/envs/michelle/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/michelle/anaconda3/envs/michelle/include/python3.6m -c _temporal_convolution_tbc.c -o ./_temporal_convolution_tbc.o -std=c++11
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
gcc -pthread -B /home/michelle/anaconda3/envs/michelle/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/michelle/anaconda3/envs/michelle/include/python3.6m -c /home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp -o ./home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
/home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp: In function ‘void TemporalConvolutionTBC_forward(const char*, void*, void*, void*, void*)’:
/home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:70:37: error: invalid initialization of non-const reference of type ‘at::Tensor&’ from an rvalue of type ‘int’
       at::addmm_out(1, O, 1, I, W, O);
                                     ^
In file included from /home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/ATen.h:10:0,
                 from /home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:12:
/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1296:24: error: in passing argument 1 of ‘at::Tensor& at::addmm_out(at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, at::Scalar, at::Scalar)’
 static inline Tensor & addmm_out(Tensor & result, const Tensor & self, const Tensor & mat1, const Tensor & mat2, Scalar beta, Scalar alpha) {
                        ^
/home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp: In function ‘void TemporalConvolutionTBC_backward(const char*, void*, void*, void*, void*, void*, void*)’:
/home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:111:52: error: invalid initialization of non-const reference of type ‘at::Tensor&’ from an rvalue of type ‘int’
       at::addmm_out(1, dI, 1, dO, weight[k].t(), dI);
                                                    ^
In file included from /home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/ATen.h:10:0,
                 from /home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:12:
/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1296:24: error: in passing argument 1 of ‘at::Tensor& at::addmm_out(at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, at::Scalar, at::Scalar)’
 static inline Tensor & addmm_out(Tensor & result, const Tensor & self, const Tensor & mat1, const Tensor & mat2, Scalar beta, Scalar alpha) {
                        ^
/home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:124:40: error: invalid initialization of non-const reference of type ‘at::Tensor&’ from an rvalue of type ‘int’
       at::addmm_out(1, dW, 1, I, dO, dW);
                                        ^
In file included from /home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/ATen.h:10:0,
                 from /home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:12:
/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1296:24: error: in passing argument 1 of ‘at::Tensor& at::addmm_out(at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, at::Scalar, at::Scalar)’
 static inline Tensor & addmm_out(Tensor & result, const Tensor & self, const Tensor & mat1, const Tensor & mat2, Scalar beta, Scalar alpha) {
                        ^
/home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:129:28: error: invalid initialization of reference of type ‘const at::Tensor&’ from expression of type ‘int’
   at::sum_out(tmp, 0, dBias);
                            ^
In file included from /home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/ATen.h:10:0,
                 from /home/michelle/mlc/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:12:
/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1137:24: error: in passing argument 2 of ‘at::Tensor& at::sum_out(at::Tensor&, const at::Tensor&, int64_t, bool)’
 static inline Tensor & sum_out(Tensor & result, const Tensor & self, int64_t dim, bool keepdim) {
                        ^
Traceback (most recent call last):
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    'build_py': build_py_hook,
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    conv_tbc.build()
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 167, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 103, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/michelle/anaconda3/envs/michelle/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1

**Comment by myleott** [comment]
It looks like it's using a version of fairseq-py from September :/

You'll want to apply at least these patches:
- https://github.com/facebookresearch/fairseq-py/commit/ae0c05d920661cc1d66f2db9c2a8073092e7df0f#diff-2a5ab91e608b50e40c864d888c84ae93
- https://github.com/facebookresearch/fairseq-py/commit/30953d8bc1155fcf734b9761de7647819797e2d7#diff-2a5ab91e608b50e40c864d888c84ae93
- https://github.com/facebookresearch/fairseq-py/commit/66314a60d86d39763ff6d02306eb8d96deab812f#diff-2a5ab91e608b50e40c864d888c84ae93

Alternatively, since you're using a new version of PyTorch, you might try manually merging these recent changes which switch FConv to use the built-in conv_tbc function in ATen: https://github.com/facebookresearch/fairseq-py/commit/56f9ec3c389a52a5786afd8152c4328d5ebea32a.

**Comment by michellegiang** [comment]
Hi,
Thank you for your support. 
It works with 3 patches when I do manually.
However, when I use git apply, it doesn't work
wget --output-document=issue1.patch https://github.com/facebookresearch/fairseq-py/commit/ae0c05d920661cc1d66f2db9c2a8073092e7df0f#diff-2a5ab91e608b50e40c864d888c84ae93.patch
git apply issue1.patch

wget --output-document=issue2.patch https://github.com/facebookresearch/fairseq-py/commit/30953d8bc1155fcf734b9761de7647819797e2d7#diff-2a5ab91e608b50e40c864d888c84ae93.patch
git apply issue2.patch

wget --output-document=issue3.patch https://github.com/facebookresearch/fairseq-py/commit/66314a60d86d39763ff6d02306eb8d96deab812f#diff-2a5ab91e608b50e40c864d888c84ae93.patch
git apply issue3.patch

**Comment by myleott** [comment]
Yes, I meant that you should do it manually. I wouldn't expect git apply to work automatically, since there's been many other changes besides those patches.

Once you've manually applied the patches and got things working, you might consider submitting a pull request to https://github.com/nusnlp/mlconvgec2018
