### ISSUE TITLE
what is left_pad ?

### ISSUE THREAD

**Issue by travel-go** [facebookresearch/fairseq-py#123]
Hello, I recently recreated fairseq.When I see learned_postitional_embedding.py,I do not particularly understand the function of self.left_pad.What do the input's data operations?
By the way, what is masked_scatter?

**Comment by myleott** [comment]
The learned positional embedding module replaces tokens with their position numbers, starting from padding_idx+1. The module also requires knowledge of whether the padding symbols will appear on the left or right side of the input. For example:
```
>>> from fairseq.modules import LearnedPositionalEmbedding
>>> pe = LearnedPositionalEmbedding(num_embeddings=8, embedding_dim=5, padding_idx=1, left_pad=True)
>>> x = torch.LongTensor([[1, 1, 5, 3, 6, 7]])
>>> x
 1  1  5  3  6  7
[torch.LongTensor of size (1,6)]
>>> pe.make_positions(x)
 1  1  2  3  4  5
[torch.LongTensor of size (1,6)]

>>> pe = LearnedPositionalEmbedding(8, 5, 1, left_pad=False)
>>> x = torch.LongTensor([[5, 3, 6, 7, 1, 1, 1]])
>>> x
    5     3     6     7     1     1     1
[torch.LongTensor of size (1,7)]
>>> pe.make_positions(x)
    2     3     4     5     1     1     1
[torch.LongTensor of size (1,7)]

```

Here are the PyTorch docs for masked_scatter: http://pytorch.org/docs/master/tensors.html?highlight=masked_scatter#torch.Tensor.masked_scatter_

**Comment by travel-go** [comment]
Thank you for your reply,it really helped me a lot

**Comment by apappu97** [comment]
Hi @myleott -- I was debugging an out of index Embedding issue I was having with running the eval_lm script for the Fan Hierarchical Model on the WritingPrompts data, and after parsing through PDB saw that some of the positional indices that were being passed into the positional embedding lookup were negative (specifically when the positions are created in LearnedPositionalEmbedding.forward() and then passed to Embedding.forward()). 

I pulled a fresh copy of master and this issue resolved itself, and I noticed that the flags for left_pad seem to be removed from LearnedPositionalEmbedding. Could you explain what the change was in terms of how the model handles padding? Thanks!

**Comment by myleott** [comment]
This is the commit: #625. Basically the old code required knowing whether to expect padding on the left or right when generating positional ids. The new version is much simpler and works regardless of where the padding is.

**Comment by apappu97** [comment]
Great, thank you for answering my question! Very helpful.
