### ISSUE TITLE
the problem of samples

### ISSUE THREAD

**Issue by travel-go** [facebookresearch/fairseq-py#125]
Hello,I'm sorry to bother you again.I donnot particularly understand about "id" and "pre_output_tokens" in samples.
What is "id"? 
How do I know the size of "id"?
Does "pre_output_tokens" mean the last sentence's tokens?

return {
            'id': id,
            'ntokens': sum(len(s['target']) for s in samples),
            'net_input': {
                'src_tokens': src_tokens,
                'src_lengths': src_lengths,
                'prev_output_tokens': prev_output_tokens,
            },
            'target': target,  
}

**Comment by hitvoice** [comment]
The "id" means the id of the training example, whose size is (batch_size,). It's not used in training but helpful when debugging.
"prev_output_tokens" are the tokens in the target sentence, which is different from "target" by one offset. It provides information on the previously generated tokens when decoding the next one.
Hope this helps :)

**Comment by travel-go** [comment]
Thank you!

**Comment by travel-go** [comment]
Thank you!
