### ISSUE TITLE
Anyway to support dynamic dataset?

### ISSUE THREAD

**Issue by getao** [facebookresearch/fairseq-py#126]
Hello. I wonder if there is a plan to support dynamic dataset, that is the training data is dynamic and different across epochs. This is a fairly practical setting in the case where the training data is too large to be loaded into memory.

Thanks.

**Comment by edunov** [comment]
I'm not aware of any plans to support dynamic dataset. How many sentences are in your dataset? Did you check the dictionary size (the most common source of memory issues)?  

If you really need to, you can try to replace IndexedInMemoryDataset with IndexedDataset here:
https://github.com/facebookresearch/fairseq-py/blob/master/fairseq/data.py#L92
and on line 89. But honestly, I have never needed it in practice and I'm using quite large datasets.
