### ISSUE TITLE
the problem of interactive.py

### ISSUE THREAD

**Issue by travel-go** [facebookresearch/fairseq-py#130]
This is my order.
CUDA_VISIBLE_DEVICES=0 python interactive.py /data/hfyu/fairseq-ch-en/data-bin -s ch -t en --path /data/hfyu/fairseq-ch-en/training_4_4layers/checkpoint_best.pt --beam 10  | tee ~/fairseq-3-2/nist02

RuntimeError: invalid argument 2: input is not contiguous at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCTensor.c:227

tihs is my pytorch version
 >>> print(torch.__version__)
0.3.1.post2

**Comment by hitvoice** [comment]
This project only supports pytorch 0.4.0. See #127.
