### ISSUE TITLE
errors when using multiple CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by gitmcdull** [facebookresearch/fairseq-py#138]
train.py works fine only if CUDA_VISIBLE_DEVICES is set with only one GPU, e.g. 
CUDA_VISIBLE_DEVICES=0,
CUDA_VISIBLE_DEVICES=1,
CUDA_VISIBLE_DEVICES=2, or
CUDA_VISIBLE_DEVICES=3. 

(1) If I use multiple devices, e.g. 
CUDA_VISIBLE_DEVICES=0,1, or
CUDA_VISIBLE_DEVICES=0,1,2,3, or
(2) If I remove the CUDA_VISIBLE_DEVICE option from the command line, 
the following error is reported:
RuntimeError: NCCL error in: /home/xxx/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:322 unhandled cuda error

Environment:
Ubuntu 14.04 LTS
4 GPUs
cuda 80
NCCL 2
anaconda

Can anyone help?

**Comment by myleott** [comment]
I haven't noticed this issue before, but it seems like NCCL is misconfigured on your system. Did you build PyTorch from source? Please try following the steps here: https://github.com/pytorch/pytorch/issues/5553.

**Comment by gitmcdull** [comment]
Thanks for your reply. 

I followed your link and realized that comment refers to NCCL1 (https://github.com/NVIDIA/nccl). But fairseq-py requires NCCL2, right?

I updated my NCCL2 from 2.0.4 to 2.1.15 following http://developer.nvidia.com/nccl. However, the problem still remains. 

Do you have any suggestions on how to verify NCCL2?

**Comment by gitmcdull** [comment]
I will check NCCL2 with nccl-tests and report the results soon.

**Comment by gitmcdull** [comment]
It seems to be a problem of my cuda driver. Thanks.
