### ISSUE TITLE
alignment dict?

### ISSUE THREAD

**Issue by mali-nuist** [facebookresearch/fairseq-py#139]
I am a fresh man of NLP,  and i encountered the problem of  unknown word replacement. I found the following codes should be used to solve this issue. I tried to  modify and run the code, but still not quiet clear how to apply this.

    # Load alignment dictionary for unknown word replacement
    # (None if no unknown word replacement, empty if no path to align dictionary)
    align_dict = utils.load_align_dict(args.replace_unk)
    ...
    hypo_tokens, hypo_str, alignment = utils.post_process_prediction(
                    hypo_tokens=hypo['tokens'].int().cpu(),
                    src_str=src_str,
                    alignment=hypo['alignment'].int().cpu(),
                    align_dict=align_dict,
                    dst_dict=dataset.dst_dict,
                    remove_bpe=args.remove_bpe,
                ) 
    ...

Does any one have any  explanations or suggestions?
thanks!

**Comment by xihajun** [comment]
@louismartin
Replace unk with original string [4815ed4](https://github.com/facebookresearch/fairseq/commit/4815ed4d5e2b50fe85573a045fdf486ff8e64a58)](https://github.com/facebookresearch/fairseq/commit/4815ed4d5e2b50fe85573a045fdf486ff8e64a58)
* Add <eos> for unk replacement
- [ ] TOCHECK

**Comment by xihajun** [comment]
> mali-nuist

Hi @mali-nuist I knew it was a long time ago, may I ask how did you solve this problem?
