### ISSUE TITLE
training and inference

### ISSUE THREAD

**Issue by piyank22** [facebookresearch/fairseq-py#14]
how is the model working in the case of inference , i cant see how in the Fconv model the decoder is working for training and inference , in the paper also i am finding a confusion as to how am suppose to get inference of this.

**Comment by myleott** [comment]
For inference we use a separate method called incremental_forward that takes a prefix and generates a single time step out output. This can be seen in the _decode method in the SequenceGenerator class.

**Comment by myleott** [comment]
For inference we use a separate method in the Decoder called _incremental_forward that takes a prefix and generates a single time step of output. This is used by the _generate and _decode methods in the SequenceGenerator class.

**Comment by piyank22** [comment]
Thanks a lot , in _incremental_forward at every step the size of x ,
[ batch_size , 1 , features ] -> [ batch_size , 2 , features ] -> [ batch_size , 3 , features ] ....
where the number are the number of words decoded , starting with end token.
would be increasing , more specifically,
i expect it to loop until we haven't found the <end> token , but it is being restricted to the number of convolution in which either we are truncating or if its shorter the <end> token is being repeated untill we have reached a specific length , which should not be a problem for a dynamic language like pytorch , i can see this issue in tensorflow , but the reason i see this is being done so keeping in mind that we are performing operations in batches and this flexibility is only possible if we have a batch size of 1 which would make it very confusing. please clarify my doubts? 

I have actually migrated to pytorch from tensorflow and in every aspect finding working on pytorch better.
but for this problem, finding it not so,
please take a look at this,

https://github.com/tensorflow/nmt#building-training-eval-and-inference-graphs

I have come to accept this idea and appreciate its beauty , there we are creating separate graphs .
so can you please elaborate on this topic as well as to why you guys have followed this approach , and if
u too feel i stick with that only in pytorch.
Thanks
