### ISSUE TITLE
Question about left_pad in data preprocessing

### ISSUE THREAD

**Issue by fyabc** [facebookresearch/fairseq-py#141]
Hello, I am trying to implement a simpler version of this model, and I have some questions when reading the code.
In `fairseq/data.py`, there are two padding constants in `LanguagePairDataset`:
```
LEFT_PAD_SOURCE = True
LEFT_PAD_TARGET = False
```
I want to know why padding symbols should appear on the left side in source sentences and on the right side in target sentences? Can I change the value of these constants? And if I change them, is the model still correct? Will it hurts the performance?

Thanks!

**Comment by edunov** [comment]
It is mostly for historical reasons. The direction of padding is important for LSTM models but plays no role in fconv. However, that doesn't mean you can flip it and expect already trained model to work correctly, you'll most likely get worse results if you do.  
So, yes, you can change it, but then you'll need to re-train your models, and then you should get very similar results.

**Comment by fyabc** [comment]
Thank you for your reply very much, I learned a lot.
