### ISSUE TITLE
preprocessing.py syntax error

### ISSUE THREAD

**Issue by danpechi** [facebookresearch/fairseq-py#15]
Hi, I'm training my own model and ran into the following error:

File "preprocess.py", line 115
    print('{} {}'.format(src_dict[k], tgt_dict[v]), file=f)
                                                        ^
SyntaxError: invalid syntax
(the carrot's at the file=f part)

I decided to make sure it wasn't just my prepare-X.sh scripts, by going through the steps listed under Training a New Model, and the same error is produced after entering the following:

python preprocess.py --source-lang de --target-lang en --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test --thresholdtgt 3 --thresholdsrc 3 --destdir data-bin/iwslt14.tokenized.de-en

Is there something I'm missing? As far as I can tell, source and target dictionaries are being properly built, so I don't know exactly what the error is hinting at.

**Comment by myleott** [comment]
What Python version are you running? It needs to be Python 3.x.

**Comment by danpechi** [comment]
Oops, that would do it. Thanks.
