### ISSUE TITLE
Checking size attribute of dst when dst is None

### ISSUE THREAD

**Issue by hrishikeshvganu** [facebookresearch/fairseq-py#2]
In the code below `if dst is None` the `dst.sizes[idx]` block  in  `Exception ...` will throw an unhandled error.

This is around https://github.com/facebookresearch/fairseq-py/blob/master/fairseq/data.py#L222
```
for idx in indices:
        # - 2 here stems from make_positions() where we offset positions
        # by padding_value + 1
        if src.sizes[idx] < 2 or \
                (dst is not None and dst.sizes[idx] < 2) or \
                sizes[idx] > max_positions - 2:
            raise Exception("Unable to handle input id {} of "
                            "size {} / {}.".format(idx, src.sizes[idx], dst.sizes[idx]))
```
To fix this `  (dst is not None and dst.sizes[idx] < 2)` can be modified to `(False if dst is None else  dst.sizes[idx] < 2)`

**Comment by edunov** [comment]
Thank you @hrishikeshvganu for finding this. It is now fixed.
