### ISSUE TITLE
fairseq PyTorch setup

### ISSUE THREAD

**Issue by slnguyen** [facebookresearch/fairseq-py#24]
I'm trying to run: `
NO_DISTRIBUTED=1 python setup.py install` to install PyTorch.

However I am getting the following error:
...
gcc -pthread -B /home/sarah/miniconda3/envs/fairseq/compiler_compat -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/sarah/miniconda3/envs/fairseq/include/python3.6m -c torch/csrc/dl.c -o build/temp.linux-x86_64-3.6/torch/csrc/dl.o
gcc -pthread -shared -B /home/sarah/miniconda3/envs/fairseq/compiler_compat -L/home/sarah/miniconda3/envs/fairseq/lib -Wl,-rpath=/home/sarah/miniconda3/envs/fairseq/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/torch/csrc/dl.o -L/home/sarah/miniconda3/envs/fairseq/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/torch/_dl.cpython-36m-x86_64-linux-gnu.so
/home/sarah/miniconda3/envs/fairseq/compiler_compat/ld: **cannot find -lpthread**
/home/sarah/miniconda3/envs/fairseq/compiler_compat/ld: **cannot find -lc**
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

How can I resolve this error?

Following [https://github.com/facebookresearch/fairseq-py/issues/19](url)

I have checked to make sure Cuda is installed. When I run `nvcc --version` I get:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

I have also added cuda headers to build path
`export CPATH=/usr/local/cuda-8.0/include`

Thanks!

**Comment by myleott** [comment]
Sorry, the instructions in the fairseq-py README have diverged slightly from the official ones.

Instead please follow the official PyTorch installation instructions: https://github.com/pytorch/pytorch#from-source.

In particular, the new instructions don't install the conda `gcc` package or any pip packages, i.e.:
```
conda install numpy pyyaml mkl setuptools cmake cffi 
conda install magma-cuda80 -c soumith
# no more pip installs
```

More details here: https://github.com/pytorch/pytorch/issues/3050

**Comment by myleott** [comment]
Good suggestion. I've updated the README to just point people to the office PyTorch installation instructions.
