### ISSUE TITLE
The epoch counter adds 1 even when loading from an unfinished checkpoint

### ISSUE THREAD

**Issue by frankang** [facebookresearch/fairseq-py#32]
Hi, I noticed that the epoch counter adds 1 even if it is loading from an unfinished last checkpoint, which saved by save_interval option. This means that if one make multiply re-trainings on multiply checkpoints within one epoch, he/she would get an accumulated count on epoch counter although the epoch itself hasn't increased yet.

I guess the related code is in utils.py file.
`epoch = state['epoch'] + 1 # _in the load_checkpoint function_`

**Comment by myleott** [comment]
I'm about to merge a number of commits, one of which will fix this issue :)
