### ISSUE TITLE
confused about the gif on readme

### ISSUE THREAD

**Issue by pangbochen** [facebookresearch/fairseq-py#35]
I am reading the paper 'Convolutional Sequence to Sequence Learning' and I am really impressed about your idea of convSeq2Seq. Thus I found this project page.
I get confused about the gif on Introduction part of readme.
In the paper Figure 1
![image](https://user-images.githubusercontent.com/26034096/31847503-fa6c115c-b64f-11e7-981a-be0db954bd29.png)
It says
![image](https://user-images.githubusercontent.com/26034096/31847514-15634c32-b650-11e7-9a5a-c164c459c80e.png)
So I think the four conv blocks in Layer 1 should compute simultaneously and for generation part also should generate four elements simultaneously.
While in the gif,
it shows one by one, not simultaneously.

**Comment by michaelauli** [comment]
The gif illustrates how the model works at inference time where only the encoder part can be computed simultaneously. The decoder network still proceeds step wise.
