### ISSUE TITLE
Gated Convolution vs Convolution

### ISSUE THREAD

**Issue by gaopeng-eugene** [facebookresearch/fairseq-py#36]

**Comment by gaopeng-eugene** [comment]
What will happen if you eliminate the gate in gated convolution? Another question, I cannot understand the position embedding in All you need is attention and Conv Seq2seq? Where does this ides come from?

**Comment by huihuifan** [comment]
The gated linear unit in the gated convolution is a non-linear activation function. If the gate is removed, the activation would only be linear. The position embedding indicates to the model which portion of the sequence the model is currently dealing with.
