### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by xvshiting** [facebookresearch/fairseq-py#39]
Namespace(batch_size=32, beam=5, cpu=False, data='/home/robert_tien/work/pytorch/models/wmt14.en-fr.fconv-py', gen_subset='test', interactive=True, lenpen=1, log_interval=1000, max_len_a=0, max_len_b=200, max_positions=1024, nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, path=['/home/robert_tien/work/pytorch/models/wmt14.en-fr.fconv-py/model.pt'], quiet=False, remove_bpe=None, seed=1, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, unk_replace_dict='', unnormalized=False, workers=1)
Traceback (most recent call last):
  File "generate.py", line 161, in <module>
    main()
  File "generate.py", line 41, in main
    dataset = data.load_with_check(args.data, [args.gen_subset], args.source_lang, args.target_lang)
  File "/home/xushiting/workspace/pytorch/fairseq-py/fairseq/data.py", line 37, in load_with_check
    src, dst = find_language_pair(os.listdir(path))
TypeError: 'NoneType' object is not iterable

**Comment by xvshiting** [comment]
` python generate.py -i \
 --path $MODEL_DIR/model.pt $MODEL_DIR \
--beam 5`
when I ran the generate code above I got the TypeError!
This is what I got when I ran `ls $MODEL_DIR`
`
bpecodes  dict.en.txt  dict.fr.txt  model.pt  README.md`

**Comment by playma** [comment]
You should give a directory path to generate.py 
And dict file is in this directory

For example
`
python generate.py fairseq-py/data-bin \
                                  -i \
                                  --path $MODEL_DIR/model.pt $MODEL_DIR \
                                  --beam 5
`

**Comment by xvshiting** [comment]
I think that because there have no .idx file in my model directory!
`def find_language_pair(files):
        for split in load_splits:
            for filename in files:
                parts = filename.split('.')
                if parts[0] == split and parts[-1] == 'idx':
                    return parts[1].split('-')
`

**Comment by xvshiting** [comment]
All right! The '.idx' and '.bin' file is all need to run the model ! I still confused about these two files, but it solved!
