### ISSUE TITLE
stack smashing detected

### ISSUE THREAD

**Issue by LMescheder** [facebookresearch/fairseq-py#43]
When I try to run the training as described in the readme, I get the following error
                                                                                                                                                                         
```
*** stack smashing detected ***: /mnt/nfs/users/t-lamesc/Apps/anaconda3/envs/torch/bin/python terminated
```                                                                                                                                                                                   

Using ipdb, I tracked the error down to [here](https://github.com/facebookresearch/fairseq-py/blob/master/fairseq/multiprocessing_trainer.py#L172). 

When I remove `CUDA_VISIBLE_DEVICES=0`, i.e. when I try to train on all 8 GPUs, I get
```
python: malloc.c:3720: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
python: malloc.c:3720: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
python: malloc.c:3720: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
python: malloc.c:3720: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
python: malloc.c:3720: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed. 
```

instead. The tests all ran okay. Any ideas?

**Comment by LMescheder** [comment]
Found the issue. It was a broken libnccl installation.
If you have time, it might be helpful to add a test that detect this.

**Comment by saranshkarira** [comment]
@LMescheder  How did you find the issue, and how did you fix the broken libnccl?
