### ISSUE TITLE
How can I rollout step by step

### ISSUE THREAD

**Issue by playma** [facebookresearch/fairseq-py#45]
Can I reuse the code in sequence_generator.py to rollout the target step by step for RL?

I want to reproduce the code in "Improving Neural Machine Translation with Conditional Sequence Generative Adversarial Nets"

<img width="800" alt="screen shot 2017-10-30 at 2 37 41 pm" src="https://user-images.githubusercontent.com/7677470/32157686-0c692e52-bd13-11e7-88f0-57178e55f31a.png">

**Comment by michaelauli** [comment]
Yes, you want to call SequenceGenerator.generate and put the model in eval mode before doing so.

**Comment by playma** [comment]
@michaelauli Thank you for your reply.
I have some problem. How can I give some sequence and rollout the whole sequence?
e.g. translate.generate('I') and get I am happy.

**Comment by michaelauli** [comment]
Take a look how it is done in generate.py, you want to do something similar.
