### ISSUE TITLE
Predicted sentences length always shorter than target sentence for long sentence

### ISSUE THREAD

**Issue by xvshiting** [facebookresearch/fairseq-py#48]
I have trained this model on some long sentences (more than 400 words). When I use it to predict , its product is shorter than target.

**Comment by xvshiting** [comment]
Is there a default setting to limit the predictions length? or It just caused by my dataset.

**Comment by myleott** [comment]
You should adjust the `--max-len-a` and `--max-len-b` options for `generate.py`. By default the maximum output length is 200 symbols: https://github.com/facebookresearch/fairseq-py/blob/master/fairseq/options.py#L94-L99.

**Comment by xvshiting** [comment]
@myleott Thanks a lot!

**Comment by xvshiting** [comment]
@myleott  I try this but it seems not work for my results.

**Comment by xvshiting** [comment]
I also tried to set length penalty, not work.

**Comment by myleott** [comment]
Can you share some more details about your dataset? What is the min/max/avg length of sentences at train and test time? What behavior are you seeing during generation? The model keeps positional embeddings, so it may be important to set the `--max-positions` argument during training (the default is 1024 positional embeddings).
