### ISSUE TITLE
Typo in  fairseq-py/preprocess.py

### ISSUE THREAD

**Issue by mitiau** [facebookresearch/fairseq-py#5]
I think

    parser.add_argument('--trainpref', metavar='FP', default='train', help='target language')

should be

    parser.add_argument('--trainpref', metavar='FP', default='train', help='comma separated, train language prefixes' )

to be in line with 

    parser.add_argument('--validpref', metavar='FP', default='valid', help='comma separated, valid language prefixes')
    parser.add_argument('--testpref', metavar='FP', default='test', help='comma separated, test language prefixes')

**Comment by edunov** [comment]
It is actually intended to be this way. While we allow you to specify multiple valid and test sets (e.g. in case of WMT you may want to use in-domain and out of domain valid sets), we do not allow you to use multiple train sets. If you want to, you need to manually join them before processing.
