### ISSUE TITLE
Log_softmax out of memory

### ISSUE THREAD

**Issue by xvshiting** [facebookresearch/fairseq-py#50]
I am so sorry for bothering you again,
The problem caused by that the lines in my `dict.*.txt` file is more than 500,000 . So it will out of memory when computing the log_softmax . 
I have two 10G GPU.
Except for adding GPUs on my machine , is there other approaches to address it ? 

Thank you!

**Comment by huihuifan** [comment]
You can (1) reduce the vocabulary size (either less tokens or use BPE) or (2) use softmax approximations such as hierarchical softmax or adaptive softmax (https://github.com/facebookresearch/adaptive-softmax)

**Comment by edunov** [comment]
@xvshiting is it intentional to use vocabulary that big?  We have a bunch of options in preprocess.py to limit the size of a vocabulary: 

```
    parser.add_argument('--thresholdtgt', metavar='N', default=0, type=int,
                        help='map words appearing less than threshold times to unknown')
    parser.add_argument('--thresholdsrc', metavar='N', default=0, type=int,
                        help='map words appearing less than threshold times to unknown')
    parser.add_argument('--nwordstgt', metavar='N', default=-1, type=int, help='number of target words to retain')
    parser.add_argument('--nwordssrc', metavar='N', default=-1, type=int, help='number of source words to retain')
```

Better yet, consider applying BPE transformation to your source data, then you will not need to deal with "unk"s

**Comment by xvshiting** [comment]
@edunov It isn't. I am used to think the BPE transformation is an default action.

**Comment by xvshiting** [comment]
@huihuifan thks! How to use the BPE? Does the fairseq-py have that function?

**Comment by xvshiting** [comment]
https://github.com/rsennrich/subword-nmt  @huihuifan @edunov  Thanks!
