### ISSUE TITLE
installation from source requires installing cffi

### ISSUE THREAD

**Issue by David-Levinthal** [facebookresearch/fairseq-py#59]
This is a very minor documentation issue
note: using python3/pip3 as there is a comment about requiring python 3 for fairseq-py
not using anaconda..I have had issues with package consistency..so I avoid it
fairseq-py installed with 
git clone https://github.com/facebookresearch/fairseq-py.git
sudo pip3 install -r requirements.txt 

levinth@zt-gpu-lin-1:~/fairseq-py$ sudo python3 setup.py build
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/__init__.py", line 12, in <module>
    import cffi
ImportError: No module named 'cffi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    from torch.utils.ffi import create_extension
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/__init__.py", line 14, in <module>
    raise ImportError("torch.utils.ffi requires the cffi package")
ImportError: torch.utils.ffi requires the cffi package
levinth@zt-gpu-lin-1:~/fairseq-py$ pip3 install cffi

and then the build worked
likely can be fixed by adding cffii to requirements.txt

**Comment by myleott** [comment]
cffi is a dependency for installing PyTorch from source [1] and they recommend installing the conda package (rather than the pip one), so I'm inclined not to add the pip version to requirements.txt.

[1] https://github.com/pytorch/pytorch#from-source

**Comment by myleott** [comment]
Actually, the conda version seems to satisfy pip (i.e., it won't get installed twice), so it probably can't hurt to add it.

**Comment by David-Levinthal** [comment]
how does the fairseq team prefer to deal with questions, assuming they even
have time to answer them?
I am trying to assemble a benchmark suite for hardware performance
evaluation (and the framework performance support provided by the vendors)
based on translators.
I would like to invoke the translators with reasonably similar models (4
layer seq2seq, first encoder is bidirectional, some bilinear/bahdanau
attention, 1024 hidden size, modes/bpe 32K vocabulary..or some such
~standard)
but also use alternate models (ie fairseq in lstm and fconv mode,
f/tensor2tensor and NMT, mxnet/sockeye..etc)
ie...make sure vendors provide good HW and SW across all (most) frameworks
??
d
