### ISSUE TITLE
bad syntax in preprocess.py

### ISSUE THREAD

**Issue by David-Levinthal** [facebookresearch/fairseq-py#60]
levinth@zt-gpu-lin-1:~/fairseq-py$ python3 preprocess.py --source-lang de --target-lang en   --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test   --destdir data-bin/iwslt14.tokenized.de-en
  File "preprocess.py", line 84
    output_text_file = os.path.join(args.destdir, f'{output_prefix}.{lang}')
                                                                          ^
SyntaxError: invalid syntax

replacing line 84 with
output_text_file = os.path.join(args.destdir, '{output_prefix}.{lang}')
appears to have fixed the issue

**Comment by myleott** [comment]
Yes, good call. This is new format string syntax introduced in Python 3.6, but I'll remove it.
