### ISSUE TITLE
What is the difference between "input_tokens" and "src_tokens"?

### ISSUE THREAD

**Issue by playma** [facebookresearch/fairseq-py#63]
Excuse me.
Anyone know what the difference is between "input_tokens" and "src_tokens"?

**Comment by myleott** [comment]
There are three main tensors created by the data loader:
- `src_tokens`: the tokens for the source sentence
- `target`: the tokens for the target sentence
- `input_tokens`: the output token produced by the decoder at $t-1$. During training this is the same as `target` but shifted by one time step (e.g., if `target = 3 4 5 6` then `input_tokens` = 0 3 4 5`. During inference this is the actual token generated in the previous time step.
