### ISSUE TITLE
RuntimeError: invalid argument 5: k not in range for dimension

### ISSUE THREAD

**Issue by sheerun** [facebookresearch/fairseq-py#7]
Not sure what's going on but I've got following result:

epoch 024 | train loss 0.15 | train ppl 1.11 | s/checkpoint    1296 | words/s   7296 | words/batch    599 | bsz   299 | lr 0.000025 | clip   0% | gnorm 0.0389
| epoch 024 | valid on 'valid' subset | valid loss 0.14 | valid ppl 1.10
| done training in 34402.3 seconds
| Test on test with beam=1: BLEU4 = 0.00, 92.3/0.0/0.0/0.0 (BP=1.000, ratio=1.000, syslen=590893, reflen=590893)
| Test on test with beam=5: BLEU4 = 0.00, 92.3/0.0/0.0/0.0 (BP=1.000, ratio=1.000, syslen=590893, reflen=590893)
Traceback (most recent call last):
  File "train.py", line 210, in <module>
    main()
  File "train.py", line 107, in main
    cuda_device=(0 if num_gpus > 0 else None))
  File "train.py", line 204, in score_test
    for _, _, ref, hypos in translator.generate_batched_itr(itr, cuda_device=cuda_device):
  File "/home/ada/fairseq-py/fairseq/sequence_generator.py", line 72, in generate_batched_itr
    maxlen=(maxlen_a*srclen + maxlen_b))
  File "/home/ada/fairseq-py/fairseq/sequence_generator.py", line 86, in generate
    return self._generate(src_tokens, src_positions, beam_size, maxlen)
  File "/home/ada/fairseq-py/fairseq/sequence_generator.py", line 232, in _generate
    probs.view(bsz, -1).topk(cand_size, out=(cand_scores, cand_indices))
RuntimeError: invalid argument 5: k not in range for dimension at /home/ada/pytorch/torch/lib/THC/generic/THCTensorTopK.cu:21

**Comment by myleott** [comment]
That errors suggests your beam size is larger than 50% of the output vocabulary size. What does the target side of your data look like? Does generation work if you set `--beam 1`?

**Comment by sheerun** [comment]
It's a small amount of classes, but I can't pinpoint the number (15-30)

**Comment by sheerun** [comment]
@myleott btw. this happens with train.py, but when I wanted to reduce beam side it complained there is no `--beam` argument

**Comment by myleott** [comment]
Yes, by default the training script runs generation at the end of training with varying beam sizes [1, 5, 10, 20], which are not configurable.

Anyway, I have pushed a fix that makes generation work with small output vocabulary sizes. Based on your log it seems like training finished, so you should be able to use `generate.py` with any beam size now and it should work.
