### ISSUE TITLE
Questions about LSTM model

### ISSUE THREAD

**Issue by ngimel** [facebookresearch/fairseq-py#71]
1) Is there a reason nn.LSTM is not used in encoder? It did not look to me like encoder is doing something special that cannot be handled by nn.LSTM
2) Any specific reason for "1000" dimension in luont_wmt_en_de https://github.com/facebookresearch/fairseq-py/blob/master/fairseq/models/lstm.py#L292-L301 (as opposed to 1024)? 1024 is usually faster.

**Comment by myleott** [comment]
1. I think you're right and we could use nn.LSTM for the encoder. It won't work for the decoder of course, but it would make the encoder faster. Good catch!

2. The default is 1000 to match Luong et al. (2015), see Section 4.1: http://aclweb.org/anthology/D15-1166.
