### ISSUE TITLE
weight normalization dimension different in encoder and decoder convolutions

### ISSUE THREAD

**Issue by burcer** [facebookresearch/fairseq-py#73]
Is there any reason why the convolution filter weights are normalized differently in encoder vs decoder during training (I am referring to weight normalization being done across different dimensions in encoder and decoder). Does it make a difference in training if one normalizes the decoder conv filters the same way as in encoder (convTBC) ? My understanding from the original weight norm paper was that weight normalization is done per output channel, whereas this does not seem to be the case in decoder of FairSeq convolutional network.

**Comment by myleott** [comment]
You're right, good catch! This issue seems to have been in fairseq-py since the initial release, but doesn't affect the Lua version. I also just did some experiments on the WMT'14 En-De dataset and it doesn't seem to make a difference (surprisingly!). In any case I'll submit a fix shortly.

**Comment by myleott** [comment]
Here some more info about the fix:

Valid loss on WMT'14 en2de:
```
epoch	before	after
1	3.91	3.92
2	3.48	3.49
3	3.27	3.28
4	3.16	3.16
5	3.09	3.09
6	3.03	3.03
7	2.99	2.99
8	2.97	2.96
9	2.93	2.92
10	2.91	2.91
11	2.89	2.89
12	2.87	2.87
13	2.86	2.86
14	2.84	2.84
15	2.84	2.83
16	2.82	2.82
17	2.81	2.81
18	2.8	2.8
19	2.8	2.79
20	2.79	2.79
21	2.79	2.78
22	2.78	2.78
23	2.77	2.77
24	2.77	2.76
25	2.76	2.76
26	2.76	2.76
27	2.75	2.75
28	2.75	2.75
29	2.75	2.74
30	2.75	2.75
31	2.75	2.74
32	2.73	2.73
33	2.73	2.73
34	2.73	2.73
35	2.73	2.73
```

BLEU on WMT'14 en2de:
```
epoch	before	fixed
30	24.05	24.27
35	24.69	24.61
```

Parameters:
```
Namespace(adam_betas='(0.9, 0.999)', arch='fconv_wmt_en_de', clip_norm=0.1, curriculum=0, data='/private/home/edunov/wmt14_en_de', decoder_attention='True', decoder_embed_dim=768, decoder_layers='[(512, 3)] * 9 + [(1024, 3)] * 4 + [(2048, 1)] * 2', decoder_out_embed_dim=512, dropout=0.2, encoder_embed_dim=768, encoder_layers='[(512, 3)] * 9 + [(1024, 3)] * 4 + [(2048, 1)] * 2', force_anneal=100, label_smoothing=0.0, log_format='json', log_interval=100, lr='1.25', lrshrink=0.1, max_epoch=0, max_sentences=None, max_source_positions=1024, max_target_positions=1024, max_tokens=4000, min_lr=1e-05, model='fconv', momentum=0.99, no_epoch_checkpoints=False, no_progress_bar=False, no_save=False, num_gpus=8, optimizer='nag', restore_file='checkpoint_last.pt', sample_without_replacement=0, save_dir='/checkpoint/myleott/wmt14_en_de.weight_norm.control.fa100.fconv.nag.lr1.25.ls0.0.clip0.1.drop0.2.maxtok4000.ngpu8.seed1', save_interval=-1, seed=1, sentence_avg=False, skip_invalid_size_inputs_valid_test=False, source_lang='en', target_lang='de', train_subset='train', valid_subset='valid', weight_decay=0.0, workers=2)
```

**Comment by burcer** [comment]
Thank you! The main reason I was asking was wnorm could run faster by updating that normalization axis, I am happy to see that it doesn't seem to make noticeable difference in BLEU.

**Comment by myleott** [comment]
It seems it is faster as well! After the fix, training on WMT'14 en2de with 8 GPUs, performance improves from 28.7k -> 29.4k target words per second.
