### ISSUE TITLE
the  gnorm=nan problem!

### ISSUE THREAD

**Issue by linhanxiao** [facebookresearch/fairseq-py#79]
when I set the weight_decay=0.1,the gnorm will be nan.why would this happen?

| epoch 001 | valid on 'valid' subset | valid loss 11.74 | valid ppl 111111111.00                                                               
| epoch 002 | train loss nan | train ppl 11111111.00 | s/checkpoint      60 | words/s   1294 | words/batch   1675 | bsz   128 | lr 0.250000 | clip  94% | gnorm nan
| epoch 002 | valid on 'valid' subset | valid loss nan | valid ppl 111111111.00                                                                 
| epoch 003 | train loss nan | train ppl 11111111.00 | s/checkpoint      58 | words/s   1323 | words/batch   1675 | bsz   128 | lr 0.250000 | clip   0% | gnorm nan
| epoch 003 | valid on 'valid' subset | valid loss nan | valid ppl 111111111.00                                                                 
| epoch 004 | train loss nan | train ppl 11111111.00 | s/checkpoint      59 | words/s   1315 | words/batch   1675 | bsz   128 | lr 0.250000 | clip   0% | gnorm nan
| epoch 004 | valid on 'valid' subset | valid loss nan | valid ppl 111111111.00                                                                 
| epoch 005 | train loss nan | train ppl 11111111.00 | s/checkpoint      59 | words/s   1317 | words/batch   1675 | bsz   128 | lr 0.250000 | clip   0% | gnorm nan
| epoch 005 | valid on 'valid' subset | valid loss nan | valid ppl 111111111.00                                                                 
| epoch 006 | train loss nan | train ppl 11111111.00 | s/checkpoint      58 | words/s   1344 | words/batch   1675 | bsz   128 | lr 0.250000 | clip   0% | gnorm nan
| epoch 006 | valid on 'valid' subset | valid loss nan | valid ppl 111111111.00                                                                 
| epoch 007 | train loss nan | train ppl 11111111.00 | s/checkpoint      58 | words/s   1319 | words/batch   1675 | bsz   128 | lr 0.250000 | clip   0% | gnorm nan
| epoch 007 @ynd @huihuifan

**Comment by huihuifan** [comment]
why does the PPL always read the same number?

**Comment by linhanxiao** [comment]
I set the ppl to  be  constant, @huihuifan ,it does not the training problem

**Comment by linhanxiao** [comment]
I set the ppl to be a constant，it isn‘t the training problem @huihuifan

**Comment by huihuifan** [comment]
this is a problem with your parameter settings, your weight decay parameter is too large. If you want to change the parameters, it's easiest to start with one of the architectures we have suggested. Further, I would advise against setting the PPL to a constant and then posting your logs in issues, because it makes it confusing to read :(

**Comment by linhanxiao** [comment]
when I set the weight_decay=0.001,the gnorm still will be nan. @huihuifan

**Comment by edunov** [comment]
I've just merged a fix for weight decay: https://github.com/facebookresearch/fairseq-py/commit/9430544a3b95dbb2e3b86c303776e37f18188ad3 

I'd recommend to set it to fairly low values, e.g. 0.000001. In my experiments 0.1 never worked. 

Also, if you still find issues while using it, please post the details of your setup (dataset, exact command that you run) and the log obtained using original version of farseq-py
