### ISSUE TITLE
can Temporalconvolution in 0.3.0 replace convTBC in fairseq-py?

### ISSUE THREAD

**Issue by jhjungCode** [facebookresearch/fairseq-py#80]
I heard new pytorch 0.3.0 uses ATEN library which is used in torch.
if it's true, Can I use nn.legacy.temporalconvolution  instead of convTBC?
and I wonder which implement has better performance.

**Comment by myleott** [comment]
I think Lua's TemporalConvolution expected input to be `B x T x C`, whereas TemporalConvolutionTBC expects input to be `T x B x C`. But there is a pull request to add `conv_tbc` into pytorch natively: https://github.com/pytorch/pytorch/pull/3730. And a corresponding PR for fairseq-py to switch to it: #66.

Out of curiosity, what's wrong with ConvTBC? :)

**Comment by jhjungCode** [comment]
actually, I havn't use fairseq with convTBC yet. 
But, I look over all codes and try to understand all python code's flow before running.
I love I can do it easily with pytorch, which is simpler(more pythonic) than tensorflow ,and it have good enough performance. 

convTBC has low level C code and special logics for speed-up. 
so, I want fairseq uses built-in function as it possible to read easily.

**Comment by myleott** [comment]
Ah. We did create a branch a while back that just used the built-in Conv1d: https://github.com/facebookresearch/fairseq-py/commit/b584b8ae045c5c1d258c88dfec0d20daca63cfe0. It's based on an old version of the code that was a bit messier overall, but it should be easier to get a sense of the model structure.
