### ISSUE TITLE
Can I train a model with fairseq (torch) and load the model with fairseq-py (pytorch)

### ISSUE THREAD

**Issue by wolfshow** [facebookresearch/fairseq-py#81]
Can I train a model with fairseq (torch) and load the model with fairseq-py (pytorch)?

**Comment by michaelauli** [comment]
No, we do not support this. You could try extracting the weights from the fairseq checkpoint, create an equivalent fairseq-py model, write it to disk and then overwrite the fairseq-py weights with the fairseq weights.

**Comment by wolfshow** [comment]
Got it. thank you!
