### ISSUE TITLE
OSError: [Errno 24] Too many open files: '/tmp/pymp-tgep00l9'

### ISSUE THREAD

**Issue by wolfshow** [facebookresearch/fairseq-py#87]
I got this error when setting encoder_layers='[(512, 3)] * 20' and decoder_layers='[(512, 3)] * 20', but when setting the layers to 4, the training is fine. How can I use more layers?

**Comment by edunov** [comment]
What is the output of  `ulimit -n`  on your system? If it's too low, maybe try to bump it up e.g.: `ulimit -n 500000`

**Comment by wolfshow** [comment]
thank you!
