### ISSUE TITLE
Please provide preprocessed and binarized training set as well

### ISSUE THREAD

**Issue by dagarcia-nvidia** [facebookresearch/fairseq-py#88]
We are trying to reproduce your results and it would be easier if you provided preprocessed and binarized training sets in addition to [the testing sets you have already made available](https://github.com/facebookresearch/fairseq-py#pre-trained-models).

Thanks!

**Comment by edunov** [comment]
Hi @dagarcia-nvidia 

I'm working on a script that will download and prepare the data. Would it be helpful?

**Comment by dagarcia-nvidia** [comment]
@edunov Sure, definitely. Thanks for the effort.

**Comment by lukmaz** [comment]
Hi @edunov ,
Are you going to publish the scripts for the data preprocessing within the next 2 weeks?
Thanks,
Lukasz

**Comment by lukmaz** [comment]
Thanks!

**Comment by lukmaz** [comment]
Hi @edunov ,
I tried to test the scripts for training WMT14 en-de, and I think some paths are messed up: 
IWSLT14 is from DE to EN,
WMT14 is from EN to DE,
but both scripts produce files ...de-en...bin/idx, e.g:
data-bin/iwslt14.tokenized.de-en/train.de-en.de.bin
data-bin/wmt14_en_de/train.de-en.de.bin

**Comment by lukmaz** [comment]
Hi @edunov ,
I played with the scripts for some time and I noticed, that WMT14_en_de script is missing test data. Are the same test data as for WMT14_en_fr going to work? I mean adding:
"http://statmt.org/wmt14/test-full.tgz" to URLS and
"test-full.tgz" to FILES

**Comment by edunov** [comment]
Thanks @lukmaz I fixed it in the latest version. 
You're correct, both scripts share the same test file

**Comment by edunov** [comment]
#91 is now landed, if there is anything else needed from us, please let us know
meanwhile, I'll close this issue
