### ISSUE TITLE
CUDA problem

### ISSUE THREAD

**Issue by travel-go** [facebookresearch/fairseq-py#98]
Hello, have a question.when I use 
CUDA_VISIBLE_DEVICES=1,2 python3 train.py /data2/hfyu/fairseq-ch-en-bpe/data-bin --lr 0.25 --clip-norm 0.1 --dropout 0.2 --max-tokens 4000 --arch fconv --save-dir /data2/hfyu/fairseq-ch-en-bpe/trainings/fconv
I meet a problem
OSError: [Errno 24] Too many open files
but when I use CUDA_VISIBLE_DEVICES=1,this problem disappears.
Does Pytorch not support multigpu?

**Comment by myleott** [comment]
You may need to increase the number of file descriptors on your system. Please check the output of `ulimit -n` on your system and, if it's too low, try increasing it: `ulimit -n 500000`

**Comment by travel-go** [comment]
Thank you for your reply
